version: '3'
services:

  #Composer Service
  composer:
    image: composer
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html

  #Node Service
  node:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
