# base image
FROM node:14.3.0

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY frontend/package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@10.1.2

# add app
COPY frontend /app
