# base image
FROM node:13.6.0 as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY frontend/package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@9.0.2

# add app
COPY frontend /app

# run tests
#RUN ng test --watch=false
#RUN ng e2e --port 4202

# generate build
RUN ng build --output-path=dist --prod

############
### prod ###
############

# base image
FROM nginx:1.17.8-alpine

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
